package storage

import (
	"haven-property/backend/internal/models"
)

func GetInitialProperties() []models.Property {
	return []models.Property{
		{
			ID:             "prop-1",
			Name:           "Kilimani Heights Apartments",
			Address:        "Kindaruma Road, off Ngong Road",
			City:           "Nairobi",
			State:          "Kilimani",
			Zip:            "00100",
			Type:           "Apartment Complex",
			ImageURL:       "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
			TotalUnits:     8,
			OccupiedUnits:  7,
			MonthlyRevenue: 535000,
			Description:    "Modern residential tower in Kilimani with high-speed lifts, borehole water backup, solar water heating, and 24/7 CCTV security.",
			YearBuilt:      2021,
			MpesaPaybill:   "880120",
			CaretakerContact: &models.CaretakerContact{
				Name:     "Mwangi Kamau (Caretaker)",
				Phone:    "+254 722 123 456",
				WhatsApp: "254722123456",
			},
			ManagerContact: models.ManagerContact{
				Name:  "Eleanor Wanjiku",
				Phone: "+254 722 555 101",
				Email: "wanjiku@havenmgmt.co.ke",
			},
		},
		{
			ID:             "prop-2",
			Name:           "Westlands Green Suites",
			Address:        "Muthithi Road, Westlands",
			City:           "Nairobi",
			State:          "Westlands",
			Zip:            "00800",
			Type:           "Residential Court",
			ImageURL:       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
			TotalUnits:     6,
			OccupiedUnits:  6,
			MonthlyRevenue: 520000,
			Description:    "Executive serviced apartments in prime Westlands near Sarit Centre. Features rooftop terrace, dedicated parking, and fiber internet.",
			YearBuilt:      2020,
			MpesaPaybill:   "880120",
			CaretakerContact: &models.CaretakerContact{
				Name:     "Otieno Peter (Caretaker)",
				Phone:    "+254 733 987 654",
				WhatsApp: "254733987654",
			},
			ManagerContact: models.ManagerContact{
				Name:  "Eleanor Wanjiku",
				Phone: "+254 722 555 101",
				Email: "wanjiku@havenmgmt.co.ke",
			},
		},
		{
			ID:             "prop-3",
			Name:           "Kileleshwa Terraces",
			Address:        "Githunguri Road, Kileleshwa",
			City:           "Nairobi",
			State:          "Kileleshwa",
			Zip:            "00100",
			Type:           "Gated Community",
			ImageURL:       "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
			TotalUnits:     4,
			OccupiedUnits:  3,
			MonthlyRevenue: 345000,
			Description:    "Spacious 3-bedroom luxury townhouses with private garden balconies, perimeter electric fence, and serene leafy surroundings.",
			YearBuilt:      2022,
			MpesaPaybill:   "880120",
			CaretakerContact: &models.CaretakerContact{
				Name:     "Kariuki Denis (Caretaker)",
				Phone:    "+254 711 334 455",
				WhatsApp: "254711334455",
			},
			ManagerContact: models.ManagerContact{
				Name:  "Eleanor Wanjiku",
				Phone: "+254 722 555 101",
				Email: "wanjiku@havenmgmt.co.ke",
			},
		},
	}
}

func GetInitialUnits() []models.Unit {
	return []models.Unit{
		// Kilimani Heights (prop-1)
		{
			ID:              "unit-101",
			PropertyID:      "prop-1",
			UnitNumber:      "4B",
			Floor:           4,
			RentAmount:      75000,
			Bedrooms:        2,
			Bathrooms:       2.0,
			Sqft:            1100,
			Status:          models.UnitStatusOccupied,
			CurrentTenantID: "tenant-1",
			LeaseStart:      "2025-01-01",
			LeaseEnd:        "2026-12-31",
			DepositAmount:   75000,
		},
		{
			ID:              "unit-102",
			PropertyID:      "prop-1",
			UnitNumber:      "1A",
			Floor:           1,
			RentAmount:      65000,
			Bedrooms:        2,
			Bathrooms:       1.5,
			Sqft:            950,
			Status:          models.UnitStatusOccupied,
			CurrentTenantID: "tenant-3",
			LeaseStart:      "2024-06-01",
			LeaseEnd:        "2026-05-31",
			DepositAmount:   65000,
		},
		{
			ID:            "unit-103",
			PropertyID:    "prop-1",
			UnitNumber:    "2B",
			Floor:         2,
			RentAmount:    75000,
			Bedrooms:      2,
			Bathrooms:     2.0,
			Sqft:          1100,
			Status:        models.UnitStatusOccupied,
			DepositAmount: 75000,
		},
		{
			ID:            "unit-104",
			PropertyID:    "prop-1",
			UnitNumber:    "3A",
			Floor:         3,
			RentAmount:    85000,
			Bedrooms:      3,
			Bathrooms:     2.5,
			Sqft:          1450,
			Status:        models.UnitStatusVacant,
			DepositAmount: 85000,
		},

		// Westlands Green Suites (prop-2)
		{
			ID:              "unit-201",
			PropertyID:      "prop-2",
			UnitNumber:      "2A",
			Floor:           2,
			RentAmount:      85000,
			Bedrooms:        2,
			Bathrooms:       2.0,
			Sqft:            1200,
			Status:          models.UnitStatusOccupied,
			CurrentTenantID: "tenant-2",
			LeaseStart:      "2024-12-01",
			LeaseEnd:        "2026-11-30",
			DepositAmount:   85000,
		},
		{
			ID:              "unit-202",
			PropertyID:      "prop-2",
			UnitNumber:      "1B",
			Floor:           1,
			RentAmount:      75000,
			Bedrooms:        2,
			Bathrooms:       1.5,
			Sqft:            1050,
			Status:          models.UnitStatusOccupied,
			CurrentTenantID: "tenant-5",
			LeaseStart:      "2025-02-01",
			LeaseEnd:        "2027-01-31",
			DepositAmount:   75000,
		},

		// Kileleshwa Terraces (prop-3)
		{
			ID:              "unit-301",
			PropertyID:      "prop-3",
			UnitNumber:      "3C",
			Floor:           3,
			RentAmount:      110000,
			Bedrooms:        3,
			Bathrooms:       3.0,
			Sqft:            1800,
			Status:          models.UnitStatusOccupied,
			CurrentTenantID: "tenant-4",
			LeaseStart:      "2025-01-15",
			LeaseEnd:        "2027-01-31",
			DepositAmount:   110000,
		},
		{
			ID:            "unit-302",
			PropertyID:    "prop-3",
			UnitNumber:    "1A",
			Floor:         1,
			RentAmount:    115000,
			Bedrooms:      3,
			Bathrooms:     3.0,
			Sqft:          1850,
			Status:        models.UnitStatusVacant,
			DepositAmount: 115000,
		},
	}
}

func GetInitialTenants() []models.Tenant {
	return []models.Tenant{
		{
			ID:               "tenant-1",
			Name:             "Juma Ochieng",
			Email:            "juma.ochieng@gmail.com",
			Phone:            "+254 712 345 678",
			PropertyID:       "prop-1",
			PropertyName:     "Kilimani Heights Apartments",
			UnitID:           "unit-101",
			UnitNumber:       "4B",
			LeaseStart:       "2025-01-01",
			LeaseEnd:         "2026-12-31",
			RentAmount:       75000,
			RentStatus:       models.RentStatusPaid,
			LastMpesaReceipt: "QKH8291KL0",
			EmergencyContact: &models.EmergencyContact{
				Name:     "Akinyi Ochieng (Sister)",
				Relation: "Sibling",
				Phone:    "+254 722 998 877",
			},
			AvatarURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:               "tenant-2",
			Name:             "Wanjiru Mwangi",
			Email:            "wanjiru.m@yahoo.com",
			Phone:            "+254 721 554 433",
			PropertyID:       "prop-2",
			PropertyName:     "Westlands Green Suites",
			UnitID:           "unit-201",
			UnitNumber:       "2A",
			LeaseStart:       "2024-12-01",
			LeaseEnd:         "2026-11-30",
			RentAmount:       85000,
			RentStatus:       models.RentStatusPaid,
			LastMpesaReceipt: "QKJ9921AA1",
			EmergencyContact: &models.EmergencyContact{
				Name:     "Kamau Mwangi (Father)",
				Relation: "Parent",
				Phone:    "+254 733 112 233",
			},
			AvatarURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:               "tenant-3",
			Name:             "Kiprono Kipkemboi",
			Email:            "kiprono.k@gmail.com",
			Phone:            "+254 728 776 655",
			PropertyID:       "prop-1",
			PropertyName:     "Kilimani Heights Apartments",
			UnitID:           "unit-102",
			UnitNumber:       "1A",
			LeaseStart:       "2024-06-01",
			LeaseEnd:         "2026-05-31",
			RentAmount:       65000,
			RentStatus:       models.RentStatusPending,
			EmergencyContact: &models.EmergencyContact{
				Name:     "Chebet Kiprono (Spouse)",
				Relation: "Spouse",
				Phone:    "+254 720 445 566",
			},
			AvatarURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:               "tenant-4",
			Name:             "Fatuma Hassan",
			Email:            "fatuma.hassan@outlook.com",
			Phone:            "+254 701 223 344",
			PropertyID:       "prop-3",
			PropertyName:     "Kileleshwa Terraces",
			UnitID:           "unit-301",
			UnitNumber:       "3C",
			LeaseStart:       "2025-01-15",
			LeaseEnd:         "2027-01-31",
			RentAmount:       110000,
			RentStatus:       models.RentStatusPaid,
			LastMpesaReceipt: "QKX3312PP8",
			EmergencyContact: &models.EmergencyContact{
				Name:     "Ali Hassan (Brother)",
				Relation: "Sibling",
				Phone:    "+254 711 778 899",
			},
			AvatarURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:               "tenant-5",
			Name:             "Brian Mutua",
			Email:            "brian.mutua@techke.org",
			Phone:            "+254 715 667 788",
			PropertyID:       "prop-2",
			PropertyName:     "Westlands Green Suites",
			UnitID:           "unit-202",
			UnitNumber:       "1B",
			LeaseStart:       "2025-02-01",
			LeaseEnd:         "2027-01-31",
			RentAmount:       75000,
			RentStatus:       models.RentStatusOverdue,
			EmergencyContact: &models.EmergencyContact{
				Name:     "Faith Mutua (Mother)",
				Relation: "Parent",
				Phone:    "+254 722 001 122",
			},
			AvatarURL: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
		},
	}
}

func GetInitialMaintenanceRequests() []models.MaintenanceRequest {
	cost1 := 4500.0
	cost3 := 3800.0

	return []models.MaintenanceRequest{
		{
			ID:              "req-1",
			TicketNumber:    "TKT-4892",
			PropertyID:      "prop-1",
			PropertyName:    "Kilimani Heights Apartments",
			UnitID:          "unit-101",
			UnitNumber:      "4B",
			TenantName:      "Juma Ochieng",
			TenantPhone:     "+254 712 345 678",
			TenantEmail:     "juma.ochieng@gmail.com",
			Title:           "Under-sink water pipe leaking into kitchen cabinet",
			Description:     "Active drip beneath the kitchen sink basin from the P-trap drainage pipe. Water collecting on cabinet floor.",
			Category:        models.CategoryPlumbing,
			Priority:        models.PriorityEmergency,
			Status:          models.StatusScheduled,
			EntryPermission: true,
			PreferredTime:   "Morning (9:00 AM - 12:00 PM)",
			CreatedAt:       "2026-08-18T08:30:00Z",
			UpdatedAt:       "2026-08-18T10:15:00Z",
			Photos: []models.DamagePhoto{
				{
					ID:        "photo-1",
					URL:       "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80",
					Caption:   "P-trap joint dripping under kitchen sink",
					Timestamp: "2026-08-18T08:25:00Z",
					Tag:       "Plumbing Joint",
				},
			},
			AssignedContractor: &models.ContractorInfo{
				Name:             "Fundi John Onyango",
				Company:          "Apex Plumbing & Drainage Nairobi",
				Phone:            "+254 722 889 900",
				WhatsApp:         "254722889900",
				ScheduledDate:    "2026-08-20",
				EstimatedArrival: "10:00 AM - 12:00 PM",
			},
			RepairCost: &cost1,
			Timeline: []models.TimelineEntry{
				{
					ID:          "time-1",
					Timestamp:   "2026-08-18T08:30:00Z",
					Author:      "Juma Ochieng",
					Role:        "tenant",
					Title:       "Breakage Ticket Logged",
					Description: "Resident submitted emergency leak report with photo evidence via QR code.",
					Type:        "creation",
				},
				{
					ID:          "time-2",
					Timestamp:   "2026-08-18T08:31:00Z",
					Author:      "Gemini AI Vision",
					Role:        "system",
					Title:       "AI Damage Inspection Completed",
					Description: "Identified P-trap compression gasket wear. Urgency rated Emergency due to potential cabinet soaking.",
					Type:        "status_change",
				},
				{
					ID:          "time-3",
					Timestamp:   "2026-08-18T10:15:00Z",
					Author:      "Eleanor Wanjiku (Landlord)",
					Role:        "landlord",
					Title:       "Fundi Dispatched",
					Description: "Assigned Fundi John Onyango from Apex Plumbing. Arrival booked for 10:00 AM.",
					Type:        "contractor",
				},
			},
			AIDiagnosis: &models.AIDiagnosis{
				CategorySummary:    "Plumbing Drainage Line Gasket Failure",
				SeverityAssessment: "Emergency: Constant moisture risks cabinet warping and floor seepage.",
				EstimatedCostRange: "KSh. 2,500 - KSh. 5,500 (Gasket replacement & pipe sealing)",
				RecommendedAction:  "Isolate cold water shutoff valve. Replace slip-joint washers and tighten collar.",
				UrgentSafetyTips: []string{
					"Turn off the angle valve under the sink",
					"Place a basin under the trap to protect cabinetry",
					"Avoid pouring boiling oil or harsh chemicals down drain",
				},
				SuggestedTrade: "Licensed Plumber / Nairobi Water Specialist",
			},
		},
		{
			ID:              "req-2",
			TicketNumber:    "TKT-4893",
			PropertyID:      "prop-2",
			PropertyName:    "Westlands Green Suites",
			UnitID:          "unit-201",
			UnitNumber:      "2A",
			TenantName:      "Wanjiru Mwangi",
			TenantPhone:     "+254 721 554 433",
			TenantEmail:     "wanjiru.m@yahoo.com",
			Title:           "Balcony sliding door latch jammed & off track",
			Description:     "Balcony aluminium glass door will not slide smoothly or lock securely from the inside.",
			Category:        models.CategoryLocksSecurity,
			Priority:        models.PriorityHigh,
			Status:          models.StatusUnderReview,
			EntryPermission: true,
			PreferredTime:   "Afternoon (2:00 PM - 5:00 PM)",
			CreatedAt:       "2026-08-18T14:20:00Z",
			UpdatedAt:       "2026-08-18T14:20:00Z",
			Photos: []models.DamagePhoto{
				{
					ID:        "photo-2",
					URL:       "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
					Caption:   "Aluminium bottom rail and latch strike plate",
					Timestamp: "2026-08-18T14:15:00Z",
					Tag:       "Door Latch",
				},
			},
			Timeline: []models.TimelineEntry{
				{
					ID:          "time-4",
					Timestamp:   "2026-08-18T14:20:00Z",
					Author:      "Wanjiru Mwangi",
					Role:        "tenant",
					Title:       "Breakage Ticket Logged",
					Description: "Resident reported security door defect.",
					Type:        "creation",
				},
			},
			AIDiagnosis: &models.AIDiagnosis{
				CategorySummary:    "Aluminium Slider Roller Alignment & Latch Fault",
				SeverityAssessment: "High: Balcony security vulnerability on lower floors.",
				EstimatedCostRange: "KSh. 3,000 - KSh. 6,500 (Roller replacement & strike realignment)",
				RecommendedAction:  "Adjust bottom tandem roller tension screws and align mortise latch.",
				UrgentSafetyTips: []string{
					"Secure secondary balcony bar lock if available",
					"Avoid forcing the glass sash",
				},
				SuggestedTrade: "Aluminium Fabricator / Locksmith",
			},
		},
		{
			ID:              "req-3",
			TicketNumber:    "TKT-4890",
			PropertyID:      "prop-3",
			PropertyName:    "Kileleshwa Terraces",
			UnitID:          "unit-301",
			UnitNumber:      "3C",
			TenantName:      "Fatuma Hassan",
			TenantPhone:     "+254 701 223 344",
			TenantEmail:     "fatuma.hassan@outlook.com",
			Title:           "Instant shower heating unit tripping main MCB breaker",
			Description:     "When switching on the master bathroom instant shower, the 20A circuit breaker trips immediately in the distribution board.",
			Category:        models.CategoryElectrical,
			Priority:        models.PriorityHigh,
			Status:          models.StatusInProgress,
			EntryPermission: false,
			PreferredTime:   "Evening (5:00 PM - 7:00 PM)",
			CreatedAt:       "2026-08-17T11:00:00Z",
			UpdatedAt:       "2026-08-19T09:00:00Z",
			Photos: []models.DamagePhoto{
				{
					ID:        "photo-3",
					URL:       "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=1000&q=80",
					Caption:   "Lorenzetti instant shower unit",
					Timestamp: "2026-08-17T10:50:00Z",
					Tag:       "Electrical Unit",
				},
			},
			AssignedContractor: &models.ContractorInfo{
				Name:             "Fundi Kariuki Mwangi",
				Company:          "Starlight Electrical Nairobi",
				Phone:            "+254 733 445 566",
				WhatsApp:         "254733445566",
				ScheduledDate:    "2026-08-19",
				EstimatedArrival: "5:30 PM",
			},
			RepairCost: &cost3,
			Timeline: []models.TimelineEntry{
				{
					ID:          "time-5",
					Timestamp:   "2026-08-17T11:00:00Z",
					Author:      "Fatuma Hassan",
					Role:        "tenant",
					Title:       "Breakage Ticket Logged",
					Description: "Instant shower short-circuit reported.",
					Type:        "creation",
				},
				{
					ID:          "time-6",
					Timestamp:   "2026-08-19T09:00:00Z",
					Author:      "Eleanor Wanjiku (Landlord)",
					Role:        "landlord",
					Title:       "Electrician Scheduled",
					Description: "Fundi Kariuki Mwangi dispatched for evening inspection.",
					Type:        "contractor",
				},
			},
			AIDiagnosis: &models.AIDiagnosis{
				CategorySummary:    "Instant Water Heater Heating Element Short",
				SeverityAssessment: "High: Tripping breaker indicates heating element burnout or earth fault.",
				EstimatedCostRange: "KSh. 2,000 - KSh. 4,500 (Element replacement or DP switch check)",
				RecommendedAction:  "Test element resistance with multimeter. Replace heating cartridge.",
				UrgentSafetyTips: []string{
					"Keep DP wall switch turned OFF until technician arrives",
					"Do not touch showerhead while power is engaged",
				},
				SuggestedTrade: "Licensed Electrician",
			},
		},
	}
}

func GetInitialUsers() []models.User {
	rentJuma := 75000.0
	rentWanjiru := 85000.0
	rentFatuma := 110000.0
	rentKiprono := 70000.0
	rentBrian := 80000.0

	return []models.User{
		{
			ID:        "user-landlord-1",
			Name:      "Eleanor Wanjiku",
			Email:     "wanjiku@havenmgmt.co.ke",
			Phone:     "+254 722 555 101",
			Password:  "haven2026",
			Role:      models.RoleLandlord,
			AvatarURL: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:           "user-tenant-1",
			Name:         "Juma Ochieng",
			Email:        "juma.ochieng@gmail.com",
			Phone:        "+254 712 345 678",
			Password:     "haven2026",
			Role:         models.RoleTenant,
			PropertyID:   "prop-1",
			PropertyName: "Kilimani Heights Apartments",
			UnitID:       "unit-102",
			UnitNumber:   "4B",
			RentAmount:   &rentJuma,
			MpesaAccount: "HAVEN-4B",
			AvatarURL:    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:           "user-tenant-2",
			Name:         "Wanjiru Mwangi",
			Email:        "wanjiru.m@gmail.com",
			Phone:        "+254 720 112 233",
			Password:     "haven2026",
			Role:         models.RoleTenant,
			PropertyID:   "prop-2",
			PropertyName: "Westlands Green Suites",
			UnitID:       "unit-201",
			UnitNumber:   "2A",
			RentAmount:   &rentWanjiru,
			MpesaAccount: "HAVEN-2A",
			AvatarURL:    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:           "user-tenant-3",
			Name:         "Fatuma Hassan",
			Email:        "fatuma.h@gmail.com",
			Phone:        "+254 733 445 566",
			Password:     "haven2026",
			Role:         models.RoleTenant,
			PropertyID:   "prop-3",
			PropertyName: "Kileleshwa Terraces",
			UnitID:       "unit-302",
			UnitNumber:   "3C",
			RentAmount:   &rentFatuma,
			MpesaAccount: "HAVEN-3C",
			AvatarURL:    "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:           "user-tenant-4",
			Name:         "Kiprono Kipkemboi",
			Email:        "kiprono.k@gmail.com",
			Phone:        "+254 711 223 344",
			Password:     "haven2026",
			Role:         models.RoleTenant,
			PropertyID:   "prop-1",
			PropertyName: "Kilimani Heights Apartments",
			UnitID:       "unit-101",
			UnitNumber:   "2A",
			RentAmount:   &rentKiprono,
			MpesaAccount: "HAVEN-2A",
			AvatarURL:    "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
		},
		{
			ID:           "user-tenant-5",
			Name:         "Brian Mutua",
			Email:        "brian.mutua@gmail.com",
			Phone:        "+254 721 889 900",
			Password:     "haven2026",
			Role:         models.RoleTenant,
			PropertyID:   "prop-2",
			PropertyName: "Westlands Green Suites",
			UnitID:       "unit-202",
			UnitNumber:   "1B",
			RentAmount:   &rentBrian,
			MpesaAccount: "HAVEN-1B",
			AvatarURL:    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
		},
	}
}
